### ISSUE TITLE
Brain should be a private attribute of dog and cat not protected in animal

### ISSUE THREAD

**Issue by RowMax03** [JonahKoellner/CPP04#1]
https://github.com/JonahKoellner/CPP04/blame/2a3d66034facac2a543b0725a68f874823378d45/ex01/Animal.hpp#L21
<img width="448" alt="image" src="https://github.com/JonahKoellner/CPP04/assets/51720224/4e6a4889-b79f-45de-a9c5-c7aa2205862a">

**Comment by JonahKoellner** [comment]
done
